name: Deploy to S3 Singapore

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_GHA_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_GHA_ACCESS_KEY }}
          aws-region: 'ap-southeast-1'
          role-to-assume: ${{ secrets.ARN_STS_ASIA }}
          role-duration-seconds: 1200
          role-skip-session-tagging: true

      - name: Upload to S3
        run: |
          aws s3 sync ./src s3://wallex-web-asset --no-progress --quiet --delete

      - name: Invalidate cache
        run: |
          aws cloudfront create-invalidation --distribution-id 'EZEVW006720HT' --paths "/*"